### ISSUE TITLE
Identity Markers? 

### ISSUE THREAD

**Issue by innat** [BCV-Uniandes/SIMBA#1]
Hello, Congratulations on your paper-work. 

However, would you please explain how you calculated chronological age for the model input? The data set contains as follows. I believe, the `Boneage` column should be the target column. 

ID | Male | Boneage
-- | -- | --
1 | False | 180
2 | True| 12

And in your paper, somehow I didn't find the experimental results on the **RSNA** data set. Would you please give some pointer?

**Comment by mc-escobar11** [comment]
Hello, 
Thanks for your interest in our work! The chronological age was provided by the expert physicians who annotated the [RHPE dataset](https://biomedicalcomputervision.uniandes.edu.co/images/papers/Hand_Pose_Estimation_for_Pediatric_Bone_Age_Assessment.pdf). We do not use the RSNA dataset in this paper precisely because it doesn't have the information of the chronological age of the patients. If you would like access to the images and the annotations of the RHPE dataset please email us at mc.escobar11@uniandes.edu.co and ci.gonzalez10@uniandes.edu.co

**Comment by innat** [comment]
Oh, I see. Thanks. I already have the data sets. -)
